name: keri
description: "Keri - Delivery Made Easy"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  hugeicons: ^1.1.4
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Backend
  supabase_flutter: ^2.0.0

  # Networking
  dio: ^5.8.0

  # Maps & Location
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.3

  # Notifications
  firebase_messaging: ^15.1.3
  firebase_core: ^3.8.0

  # Utils
  intl: ^0.20.2
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.4

  # UI
  modal_bottom_sheet: ^3.0.0
  lottie: ^3.1.3
  url_launcher: ^6.3.1
  toastification: ^2.3.0
  image_picker: ^1.1.2
  vibration: ^3.1.5
  pinput: ^5.0.0
  dropdown_button2: ^2.3.9

  cupertino_icons: ^1.0.8
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_package_name: ^1.1.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  # assets
  assets:
    - assets/images/
    - assets/lotties/
    - .env

  fonts:
      - family: Figtree
        fonts:
          - asset: assets/fonts/Figtree-Light.ttf
            weight: 300
          - asset: assets/fonts/Figtree-Regular.ttf
            weight: 400
          - asset: assets/fonts/Figtree-Medium.ttf
            weight: 500
          - asset: assets/fonts/Figtree-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Figtree-Bold.ttf
            weight: 700